-- AUTO-GENERATED by scripts/python/loader.py -- do not edit by hand.
-- Column types are inferred from the CSV files in data/.
-- Regenerate with: uv run scripts/python/load_data.py

CREATE SCHEMA IF NOT EXISTS raw_data;


-- CREATE table customers

DROP TABLE IF EXISTS raw_data.customers CASCADE;

CREATE TABLE raw_data.customers (
    customer_id BIGINT PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(20),
    email VARCHAR(100),
    phone VARCHAR(50),
    city VARCHAR(50),
    province VARCHAR(50),
    country VARCHAR(50),
    created_timestamp TIMESTAMP,
    updated_timestamp TIMESTAMP,
    is_active CHAR(1)
);


-- CREATE table employees

DROP TABLE IF EXISTS raw_data.employees CASCADE;

CREATE TABLE raw_data.employees (
    employee_id BIGINT PRIMARY KEY,
    store_id BIGINT,
    first_name VARCHAR(20),
    last_name VARCHAR(20),
    email VARCHAR(100),
    job_title VARCHAR(100),
    salary NUMERIC(11, 2),
    created_timestamp TIMESTAMP,
    updated_timestamp TIMESTAMP,
    is_active CHAR(1)
);


-- CREATE table order_items

DROP TABLE IF EXISTS raw_data.order_items CASCADE;

CREATE TABLE raw_data.order_items (
    order_item_id BIGINT PRIMARY KEY,
    order_id BIGINT,
    product_id BIGINT,
    quantity INTEGER,
    unit_price NUMERIC(10, 2),
    line_amount NUMERIC(10, 2),
    created_timestamp TIMESTAMP,
    updated_timestamp TIMESTAMP,
    is_active CHAR(1)
);


-- CREATE table orders

DROP TABLE IF EXISTS raw_data.orders CASCADE;

CREATE TABLE raw_data.orders (
    order_id BIGINT PRIMARY KEY,
    customer_id BIGINT,
    store_id BIGINT,
    order_timestamp TIMESTAMP,
    payment_method VARCHAR(50),
    order_status VARCHAR(20),
    total_amount NUMERIC(10, 2),
    created_timestamp TIMESTAMP,
    updated_timestamp TIMESTAMP,
    is_active CHAR(1)
);


-- CREATE table products

DROP TABLE IF EXISTS raw_data.products CASCADE;

CREATE TABLE raw_data.products (
    product_id BIGINT PRIMARY KEY,
    product_name VARCHAR(100),
    category VARCHAR(50),
    brand VARCHAR(50),
    price NUMERIC(10, 2),
    created_timestamp TIMESTAMP,
    updated_timestamp TIMESTAMP,
    is_active CHAR(1)
);


-- CREATE table stores

DROP TABLE IF EXISTS raw_data.stores CASCADE;

CREATE TABLE raw_data.stores (
    store_id BIGINT PRIMARY KEY,
    store_name VARCHAR(100),
    city VARCHAR(50),
    province VARCHAR(50),
    country VARCHAR(50),
    created_timestamp TIMESTAMP,
    updated_timestamp TIMESTAMP,
    is_active CHAR(1)
);
